baseurl = "/"
languageCode = "en-us"
title = "Another Random Blog"
theme = "hugo-classic"
googleAnalytics = "UA-107230532-2"
disqusShortname = "tcblogsitetest"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4
[[menu.main]]
    name = "slides"
    url = "/myslides/"

[params]
    description = "A website built through Hugo and blogdown."
    footer = "Powered by hugo, netlify and blogdown <br> <i class='fa fa-copyright' aria-hidden='true'></i>  [TC](https://tctc.netlify.com) 2017-2018 | [<i class='fa fa-github' aria-hidden='true'></i>](https://github.com/tcgriffith) | [<i class='fa fa-twitter' aria-hidden='true'></i>](https://twitter.com/ustcer_ztc)| [<i class='fa fa-google' aria-hidden='true'></i>](mailto:ztc.ustcer@gmail.com)"
    enableGitalk = true
  
[params.gitalk]
    clientID = "80e8ee2d8b0f04a52c2e" # Your client ID
    clientSecret = "4ccbae190e72ec2e6b8fbd8b57f3b77269efdc95" # Your client secret
    repo = "gitalkcomments" # The repo to store comments
    owner = "tcgriffith" # Your GitHub ID
    admin= "tcgriffith" # Required. Github repository owner and collaborators. (Users who having write access to this repository)
    id= "location.pathname" # The unique id of the page.
    labels= "gitalk" # Github issue labels. If you used to use Gitment, you can change it
    perPage= 15 # Pagination size, with maximum 100.
    pagerDirection= "last" # Comment sorting direction, available values are 'last' and 'first'.
    createIssueManually= false # If it is 'false', it is auto to make a Github issue when the administrators login.
    distractionFreeMode= false # Enable hot key (cmd|ctrl + enter) submit comment.