---
title: "My Summary of 2018"
author: "Tongchuan Zhang"
date: "2018/12/10 (updated: `r Sys.Date()`)"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
```


class: center, middle, inverse
### Progress bar for 2018：▓▓▓▓▓▓▓▓▓▓▓▓▓▓░     97%


---

class: bottom, right, inverse

# Projects

---

# Cancer mutation analysis

.footnote[
*In collaboration with Prof. Jiri Neuzil
]

- What  
    - Cancer cells without mitochondrial DNA do not form tumors unless they can highjack host mitochondria.  
    - Colleagues pinned down to gene DHODH (and its pathway).  
    - Our data analysis implies that the mutation rate of DHODH and related genes are below-average, which supports the argument that these genes may be important to tumor development.  

- Status: paper published
- Things learned:
    - Mutation data analysis
    - Use of SQL to handle large dataset

---
# DFIRE_RNA

- What
    - RNA can form tertiary 3D structures and biological functions
    - experimental RNA structures are limited -> build computational RNA models
    - DFIRE_RNA is an RNA statistical energy function to evaluate RNA models.

--

- Status: 
    - Drafting the paper

--

- Things learned:
    - lots, lots of C++ stuff
    - Not procrastinate and push forward.
    - how to handle `stack overflow` and `segmentation fault`


---
# SPalign_RNA

- What
    - A tool to evaluate structure similarity between RNA structures.

--

- Output: 
    - temporarily paused because RMalign performs better (longer alignment length with lower RMSD)

--

- Things learned:
    - Built upon Peter's codebase 
    - Dynamic programming, sequence alignment algorithms

---

.footnote[
*In collaboration with Jaswinder
]

# RNA secondary structure prediction


- What
    - To further improve the RNA SS prediction 
    
    
- Status: started

---

# Summary

- Things I think I'm doing good
    - Regular physical exercises (Thanks, XP & Hector!)
    - Get 1637 reputation on Stack overflow
    - I'm a fast learner
        - HTML+CSS+JS
        - Japanese
        - All things related to R

- There are still lots of things I need to improve
    - Stop procrastinating and do the real work
    - Make moves quicker & communicate more.